### ISSUE TITLE
Menu link options are empty

### ISSUE THREAD

**Issue by pe7er** [joomla-projects/gsoc16_menu-for-article#18] opened 2016-07-22 08:50 UTC
#### Steps to reproduce the issue

Create a new article, open [Menu link options],
add some Menu Title (eg "Some new menu"),
**do not change** "Menu name" (keep it About Joomla) 
and Parent Item (Keep Menu Item Root)
& Save.
#### Expected result

I would expect a new menu item in the About Joomla menu,
and that the fields in "Menu link options" would show that.
#### Actual result

All fields in "Menu link options" are empty.
However, under Menus > About Joomla, there's a new menu item 
called "Some new menu" and its state is unpublished.
#### Remark

I am not sure when/why this behavior is caused
Is it with new articles (ID=0) and jform[menutype] has not been chosen (so with the default 1st option About Joomla)?

**Comment by shubhamnba2009** [comment] 2016-07-22 18:13
I was unable to reproduce this error..
1. Created new article.
2. Went in menu link options tab.
3. Changed nothing except menu title.
4. clicked on save.
5. Menu saved successfully.

@gunjanpatel Can you reproduce this bug?

**Comment by gunjanpatel** [comment] 2016-07-25 05:43
No I am not able to reproduce this issue.

**Comment by shubhamnba2009** [comment] 2016-07-28 12:28
Since this bug is not reproducable.. I am closing this issue

**Closed as completed by shubhamnba2009** 2016-07-28 12:28 UTC
Labels: bug
